log-level: "debug"
file_service:
    name: "file_service"
    host: "0.0.0.0"
    port: 8000
storage_service:
    name: "storage_service"
    host: "0.0.0.0"
    port: 8001
user_service:
    name: "user_service"
    host: "0.0.0.0"
    port: 8080
storage:
    type: "local"
    endpoint: "162.14.115.114:9000"
    access_key_id: "test-minio"
    secret_access_key: "12345678"
    block_size: 102400
    use_ssl: false
    bucket_name: "test"
    real_path: "./storage-01"
pg:
    host: "162.14.115.114"
    port: 5432
    user: "cill"
    password: "12345678"
    db_name: "test"

redis:
    addr: "162.14.115.114:6379"
    password: "12345678"
    db: 0
    unique_value: 1

mq:
    addr: "162.14.115.114:5672"
    username: "cill"
    password: "12345678"

storageRPC:
    domain: "storage-rpc"
    endpoints: "storage-rpc:9000"
    is_remote: false

fileRPC:
    domain: "file-rpc"
    endpoints: "file-rpc:9001"

userRPC:
    domain: "user-rpc"
    endpoints: "user-rpc:50001"