log-level: "debug"
cloud_storage:
    name: "cloud-file"
    host: "0.0.0.0"
    port: 8000
storage:
    type: "minio"
    endpoint: "162.14.115.114:9000"
    access_key_id: "cill"
    secret_access_key: "12345678"
    use_ssl: false
    bucket_name: "test-bucket"
pg:
    host: "162.14.115.114"
    port: 5432
    user: "cill"
    password: "12345678"
    db_name: "test"

file:
    block_size: 5*1024*1024

redis:
    addr: "162.14.115.114:6379"
    password: "12345678"
    db: 0

storageRPC:
    domain: "storageRPC"
    endpoints: "127.0.0.1"